name:                bathroomStalls
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/bathroomStalls#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text

executables:
  bathroomStalls:
    source-dirs:      src
    main:             BathroomStall.hs
